const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    firstName: "Arjun",
    password: "123",
    taskCounts: {
      new: 1,
      complete: 2,
      progress: 3,
      failed: 1,
    },
    tasks: [
      {
        title: "Design Homepage",
        description: "Create responsive UI for homepage",
        date: "2025-08-23",
        category: "Design",
        active: true,
        newTask: true,
        complete: false,
        failed: false,
      },
      {
        title: "Fix Navbar Bug",
        description: "Resolve alignment issue in navbar",
        date: "2025-08-25",
        category: "Bug Fix",
        active: false,
        newTask: false,
        complete: true,
        failed: false,
      },
      {
        title: "Update Dashboard",
        description: "Add statistics cards to dashboard",
        date: "2025-08-28",
        category: "Development",
        active: true,
        newTask: false,
        complete: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    firstName: "Neha",
    password: "123",
    taskCounts: { 
      new: 1, 
      complete: 2, 
      progress: 3, 
      failed: 1 
    },
    tasks: [
      {
        title: "API Integration",
        description: "Integrate payment API with backend",
        date: "2025-08-24",
        category: "Backend",
        active: true,
        newTask: true,
        complete: false,
        failed: false,
      },
      {
        title: "Testing Auth Flow",
        description: "Check login and signup functionality",
        date: "2025-08-26",
        category: "Testing",
        active: false,
        newTask: false,
        complete: true,
        failed: false,
      },
      {
        title: "Write Docs",
        description: "Prepare documentation for API endpoints",
        date: "2025-08-29",
        category: "Documentation",
        active: false,
        newTask: false,
        complete: false,
        failed: true,
      },
      {
        title: "Optimize Queries",
        description: "Improve performance of SQL queries",
        date: "2025-09-01",
        category: "Database",
        active: true,
        newTask: false,
        complete: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    firstName: "Shubham",
    password: "123",
    taskCounts: {
      new: 5,
      complete: 10,
      progress: 3,
      failed: 1,
    },
    tasks: [
      {
        title: "Client Meeting",
        description: "Discuss project requirements with client",
        date: "2025-08-23",
        category: "Management",
        active: true,
        newTask: true,
        complete: false,
        failed: false,
      },
      {
        title: "Design Wireframes",
        description: "Prepare wireframes for new features",
        date: "2025-08-27",
        category: "Design",
        active: false,
        newTask: false,
        complete: true,
        failed: false,
      },
      {
        title: "Fix Deployment",
        description: "Resolve errors in production build",
        date: "2025-08-30",
        category: "DevOps",
        active: false,
        newTask: false,
        complete: false,
        failed: true,
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    firstName: "udita",
    password: "123",
    taskCounts: {
      new: 1,
      complete: 2,
      progress: 3,
      failed: 1,
    },
    tasks: [
      {
        title: "Code Review",
        description: "Review pull requests from teammates",
        date: "2025-08-24",
        category: "Code Review",
        active: true,
        newTask: true,
        complete: false,
        failed: false,
      },
      {
        title: "Update Styles",
        description: "Refactor Tailwind classes for consistency",
        date: "2025-08-26",
        category: "Frontend",
        active: false,
        newTask: false,
        complete: true,
        failed: false,
      },
      {
        title: "Write Unit Tests",
        description: "Add test cases for user services",
        date: "2025-08-28",
        category: "Testing",
        active: true,
        newTask: false,
        complete: false,
        failed: false,
      },
      {
        title: "Database Backup",
        description: "Schedule weekly database backup",
        date: "2025-08-29",
        category: "Database",
        active: false,
        newTask: false,
        complete: false,
        failed: true,
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    firstName: "sohan",
    password: "123",
    taskCounts: {
      new: 1,
      complete: 2,
      progress: 3,
      failed: 1,
    },
    tasks: [
      {
        title: "Refactor Code",
        description: "Clean up unused components",
        date: "2025-08-23",
        category: "Development",
        active: true,
        newTask: true,
        complete: false,
        failed: false,
      },
      {
        title: "Security Audit",
        description: "Run security checks on APIs",
        date: "2025-08-27",
        category: "Security",
        active: false,
        newTask: false,
        complete: true,
        failed: false,
      },
      {
        title: "Client Report",
        description: "Prepare weekly progress report",
        date: "2025-08-30",
        category: "Documentation",
        active: false,
        newTask: false,
        complete: false,
        failed: true,
      },
    ],
  },
];

const admin = [
  {
    id: 101,
    email: "admin@example.com",
    firstName: "Arghavan",
    password: "123",
     taskCounts: { 
      new: 1, 
      complete: 2, 
      progress: 3, 
      failed: 1 
    },
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
